# Generated by Django 4.2.19 on 2026-08-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor', models.CharField(max_length=120, verbose_name='Créancier')),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant initial')),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant restant')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='Date d échéance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('ouverte', 'À payer'), ('payee', 'Payée')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dette',
                'verbose_name_plural': 'Dettes',
                'ordering': ['statut', 'date_echeance', '-created_at'],
            },
        ),
    ]
