services:
  - type: web
    name: mny-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        generateValue: true
      - key: DB_USER
        generateValue: true
      - key: DB_PASSWORD
        generateValue: true
      - key: DB_HOST
        generateValue: true
      - key: DB_PORT
        value: "5432"
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "mny-backend.onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True

  - type: web
    name: mny-frontend
    env: static
    region: frankfurt
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://mny-backend.onrender.com/api