# Generated by Django 4.2 on 2026-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_add_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('alimentation', 'Alimentation'), ('transport', 'Transport'), ('logement', 'Logement'), ('loisirs', 'Loisirs'), ('sante', 'Santé'), ('education', 'Éducation'), ('shopping', 'Shopping'), ('salaire', 'Salaire'), ('freelance', 'Freelance'), ('investissement', 'Investissement'), ('vente', 'Vente'), ('autres', 'Autres')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
