# Generated by Django 4.2.19 on 2026-08-26 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0004_alter_expense_categorie_revenuesource_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_day', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateField()),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Résilié')], default='active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.DateField()),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_charge', to='expenses.expense')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-billing_period'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptioncharge',
            constraint=models.UniqueConstraint(fields=('subscription', 'billing_period'), name='unique_subscription_period'),
        ),
    ]
