# Generated by Django 4.2 on 2026-07-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('alimentation', 'Alimentation'), ('transport', 'Transport'), ('logement', 'Logement'), ('loisirs', 'Loisirs'), ('sante', 'Santé'), ('education', 'Éducation'), ('shopping', 'Shopping'), ('autres', 'Autres')], max_length=20, verbose_name='Catégorie')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant budget')),
                ('mois', models.DateField(help_text='Premier jour du mois (ex: 2026-07-01)', verbose_name='Mois')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-mois', 'categorie'],
                'unique_together': {('user', 'categorie', 'mois')},
            },
        ),
    ]
