# Generated by Django 4.2 — catégories de budget libres (custom categories)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='categorie',
            field=models.CharField(max_length=50, verbose_name='Catégorie'),
        ),
    ]